import type { RawProblemSetEntry } from "./problemSets";

// Generated from official LeetCode study-plan data.
// Refresh with: node scripts/update-problem-set-data.mjs
export const RAW_PROBLEM_SET_ENTRIES = [
  // LeetCode 75
  ["leetcode-75","Array / String","1768","merge-strings-alternately","Merge Strings Alternately","EASY","Two Pointers|String"],
  ["leetcode-75","Array / String","1071","greatest-common-divisor-of-strings","Greatest Common Divisor of Strings","EASY","Math|String"],
  ["leetcode-75","Array / String","1431","kids-with-the-greatest-number-of-candies","Kids With the Greatest Number of Candies","EASY","Array"],
  ["leetcode-75","Array / String","605","can-place-flowers","Can Place Flowers","EASY","Array|Greedy"],
  ["leetcode-75","Array / String","345","reverse-vowels-of-a-string","Reverse Vowels of a String","EASY","Two Pointers|String"],
  ["leetcode-75","Array / String","151","reverse-words-in-a-string","Reverse Words in a String","MEDIUM","Two Pointers|String"],
  ["leetcode-75","Array / String","238","product-of-array-except-self","Product of Array Except Self","MEDIUM","Array|Prefix Sum"],
  ["leetcode-75","Array / String","334","increasing-triplet-subsequence","Increasing Triplet Subsequence","MEDIUM","Array|Greedy"],
  ["leetcode-75","Array / String","443","string-compression","String Compression","MEDIUM","Two Pointers|String"],
  ["leetcode-75","Two Pointers","283","move-zeroes","Move Zeroes","EASY","Array|Two Pointers"],
  ["leetcode-75","Two Pointers","392","is-subsequence","Is Subsequence","EASY","Two Pointers|String|Dynamic Programming"],
  ["leetcode-75","Two Pointers","11","container-with-most-water","Container With Most Water","MEDIUM","Array|Two Pointers|Greedy"],
  ["leetcode-75","Two Pointers","1679","max-number-of-k-sum-pairs","Max Number of K-Sum Pairs","MEDIUM","Array|Hash Table|Two Pointers|Sorting"],
  ["leetcode-75","Sliding Window","643","maximum-average-subarray-i","Maximum Average Subarray I","EASY","Array|Sliding Window"],
  ["leetcode-75","Sliding Window","1456","maximum-number-of-vowels-in-a-substring-of-given-length","Maximum Number of Vowels in a Substring of Given Length","MEDIUM","String|Sliding Window"],
  ["leetcode-75","Sliding Window","1004","max-consecutive-ones-iii","Max Consecutive Ones III","MEDIUM","Array|Binary Search|Sliding Window|Prefix Sum"],
  ["leetcode-75","Sliding Window","1493","longest-subarray-of-1s-after-deleting-one-element","Longest Subarray of 1's After Deleting One Element","MEDIUM","Array|Dynamic Programming|Sliding Window"],
  ["leetcode-75","Prefix Sum","1732","find-the-highest-altitude","Find the Highest Altitude","EASY","Array|Prefix Sum"],
  ["leetcode-75","Prefix Sum","724","find-pivot-index","Find Pivot Index","EASY","Array|Prefix Sum"],
  ["leetcode-75","Hash Map / Set","2215","find-the-difference-of-two-arrays","Find the Difference of Two Arrays","EASY","Array|Hash Table"],
  ["leetcode-75","Hash Map / Set","1207","unique-number-of-occurrences","Unique Number of Occurrences","EASY","Array|Hash Table"],
  ["leetcode-75","Hash Map / Set","1657","determine-if-two-strings-are-close","Determine if Two Strings Are Close","MEDIUM","Hash Table|String|Sorting|Counting"],
  ["leetcode-75","Hash Map / Set","2352","equal-row-and-column-pairs","Equal Row and Column Pairs","MEDIUM","Array|Hash Table|Matrix|Simulation"],
  ["leetcode-75","Stack","2390","removing-stars-from-a-string","Removing Stars From a String","MEDIUM","String|Stack|Simulation"],
  ["leetcode-75","Stack","735","asteroid-collision","Asteroid Collision","MEDIUM","Array|Stack|Simulation"],
  ["leetcode-75","Stack","394","decode-string","Decode String","MEDIUM","String|Stack|Recursion"],
  ["leetcode-75","Queue","933","number-of-recent-calls","Number of Recent Calls","EASY","Design|Queue|Data Stream"],
  ["leetcode-75","Queue","649","dota2-senate","Dota2 Senate","MEDIUM","String|Greedy|Queue"],
  ["leetcode-75","Linked List","2095","delete-the-middle-node-of-a-linked-list","Delete the Middle Node of a Linked List","MEDIUM","Linked List|Two Pointers"],
  ["leetcode-75","Linked List","328","odd-even-linked-list","Odd Even Linked List","MEDIUM","Linked List"],
  ["leetcode-75","Linked List","206","reverse-linked-list","Reverse Linked List","EASY","Linked List|Recursion"],
  ["leetcode-75","Linked List","2130","maximum-twin-sum-of-a-linked-list","Maximum Twin Sum of a Linked List","MEDIUM","Linked List|Two Pointers|Stack"],
  ["leetcode-75","Binary Tree - DFS","104","maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","872","leaf-similar-trees","Leaf-Similar Trees","EASY","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","1448","count-good-nodes-in-binary-tree","Count Good Nodes in Binary Tree","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","437","path-sum-iii","Path Sum III","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","1372","longest-zigzag-path-in-a-binary-tree","Longest ZigZag Path in a Binary Tree","MEDIUM","Dynamic Programming|Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","236","lowest-common-ancestor-of-a-binary-tree","Lowest Common Ancestor of a Binary Tree","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - BFS","199","binary-tree-right-side-view","Binary Tree Right Side View","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - BFS","1161","maximum-level-sum-of-a-binary-tree","Maximum Level Sum of a Binary Tree","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Search Tree","700","search-in-a-binary-search-tree","Search in a Binary Search Tree","EASY","Tree|Binary Search Tree|Binary Tree"],
  ["leetcode-75","Binary Search Tree","450","delete-node-in-a-bst","Delete Node in a BST","MEDIUM","Tree|Binary Search Tree|Binary Tree"],
  ["leetcode-75","Graphs - DFS","841","keys-and-rooms","Keys and Rooms","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory"],
  ["leetcode-75","Graphs - DFS","547","number-of-provinces","Number of Provinces","MEDIUM","Depth-First Search|Breadth-First Search|Union-Find|Graph Theory"],
  ["leetcode-75","Graphs - DFS","1466","reorder-routes-to-make-all-paths-lead-to-the-city-zero","Reorder Routes to Make All Paths Lead to the City Zero","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory"],
  ["leetcode-75","Graphs - DFS","399","evaluate-division","Evaluate Division","MEDIUM","Array|String|Depth-First Search|Breadth-First Search|Union-Find|Graph Theory|Shortest Path"],
  ["leetcode-75","Graphs - BFS","1926","nearest-exit-from-entrance-in-maze","Nearest Exit from Entrance in Maze","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["leetcode-75","Graphs - BFS","994","rotting-oranges","Rotting Oranges","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["leetcode-75","Heap / Priority Queue","215","kth-largest-element-in-an-array","Kth Largest Element in an Array","MEDIUM","Array|Divide and Conquer|Sorting|Heap (Priority Queue)|Quickselect"],
  ["leetcode-75","Heap / Priority Queue","2336","smallest-number-in-infinite-set","Smallest Number in Infinite Set","MEDIUM","Hash Table|Design|Heap (Priority Queue)|Ordered Set"],
  ["leetcode-75","Heap / Priority Queue","2542","maximum-subsequence-score","Maximum Subsequence Score","MEDIUM","Array|Greedy|Sorting|Heap (Priority Queue)"],
  ["leetcode-75","Heap / Priority Queue","2462","total-cost-to-hire-k-workers","Total Cost to Hire K Workers","MEDIUM","Array|Two Pointers|Heap (Priority Queue)|Simulation"],
  ["leetcode-75","Binary Search","374","guess-number-higher-or-lower","Guess Number Higher or Lower","EASY","Binary Search|Interactive"],
  ["leetcode-75","Binary Search","2300","successful-pairs-of-spells-and-potions","Successful Pairs of Spells and Potions","MEDIUM","Array|Two Pointers|Binary Search|Sorting"],
  ["leetcode-75","Binary Search","162","find-peak-element","Find Peak Element","MEDIUM","Array|Binary Search"],
  ["leetcode-75","Binary Search","875","koko-eating-bananas","Koko Eating Bananas","MEDIUM","Array|Binary Search"],
  ["leetcode-75","Backtracking","17","letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","MEDIUM","Hash Table|String|Backtracking"],
  ["leetcode-75","Backtracking","216","combination-sum-iii","Combination Sum III","MEDIUM","Array|Backtracking"],
  ["leetcode-75","DP - 1D","1137","n-th-tribonacci-number","N-th Tribonacci Number","EASY","Math|Dynamic Programming|Memoization"],
  ["leetcode-75","DP - 1D","746","min-cost-climbing-stairs","Min Cost Climbing Stairs","EASY","Array|Dynamic Programming"],
  ["leetcode-75","DP - 1D","198","house-robber","House Robber","MEDIUM","Array|Dynamic Programming"],
  ["leetcode-75","DP - 1D","790","domino-and-tromino-tiling","Domino and Tromino Tiling","MEDIUM","Dynamic Programming"],
  ["leetcode-75","DP - Multidimensional","62","unique-paths","Unique Paths","MEDIUM","Math|Dynamic Programming|Combinatorics"],
  ["leetcode-75","DP - Multidimensional","1143","longest-common-subsequence","Longest Common Subsequence","MEDIUM","String|Dynamic Programming"],
  ["leetcode-75","DP - Multidimensional","714","best-time-to-buy-and-sell-stock-with-transaction-fee","Best Time to Buy and Sell Stock with Transaction Fee","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["leetcode-75","DP - Multidimensional","72","edit-distance","Edit Distance","MEDIUM","String|Dynamic Programming"],
  ["leetcode-75","Bit Manipulation","338","counting-bits","Counting Bits","EASY","Dynamic Programming|Bit Manipulation"],
  ["leetcode-75","Bit Manipulation","136","single-number","Single Number","EASY","Array|Bit Manipulation"],
  ["leetcode-75","Bit Manipulation","1318","minimum-flips-to-make-a-or-b-equal-to-c","Minimum Flips to Make a OR b Equal to c","MEDIUM","Bit Manipulation"],
  ["leetcode-75","Trie","208","implement-trie-prefix-tree","Implement Trie (Prefix Tree)","MEDIUM","Hash Table|String|Design|Trie"],
  ["leetcode-75","Trie","1268","search-suggestions-system","Search Suggestions System","MEDIUM","Array|String|Binary Search|Trie|Sorting|Heap (Priority Queue)"],
  ["leetcode-75","Intervals","435","non-overlapping-intervals","Non-overlapping Intervals","MEDIUM","Array|Dynamic Programming|Greedy|Sorting"],
  ["leetcode-75","Intervals","452","minimum-number-of-arrows-to-burst-balloons","Minimum Number of Arrows to Burst Balloons","MEDIUM","Array|Greedy|Sorting"],
  ["leetcode-75","Monotonic Stack","739","daily-temperatures","Daily Temperatures","MEDIUM","Array|Stack|Monotonic Stack"],
  ["leetcode-75","Monotonic Stack","901","online-stock-span","Online Stock Span","MEDIUM","Stack|Design|Monotonic Stack|Data Stream"],
  // Top Interview 150
  ["top-interview-150","Array / String","88","merge-sorted-array","Merge Sorted Array","EASY","Array|Two Pointers|Sorting"],
  ["top-interview-150","Array / String","27","remove-element","Remove Element","EASY","Array|Two Pointers"],
  ["top-interview-150","Array / String","26","remove-duplicates-from-sorted-array","Remove Duplicates from Sorted Array","EASY","Array|Two Pointers"],
  ["top-interview-150","Array / String","80","remove-duplicates-from-sorted-array-ii","Remove Duplicates from Sorted Array II","MEDIUM","Array|Two Pointers"],
  ["top-interview-150","Array / String","169","majority-element","Majority Element","EASY","Array|Hash Table|Divide and Conquer|Sorting|Counting"],
  ["top-interview-150","Array / String","189","rotate-array","Rotate Array","MEDIUM","Array|Math|Two Pointers"],
  ["top-interview-150","Array / String","121","best-time-to-buy-and-sell-stock","Best Time to Buy and Sell Stock","EASY","Array|Dynamic Programming"],
  ["top-interview-150","Array / String","122","best-time-to-buy-and-sell-stock-ii","Best Time to Buy and Sell Stock II","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","55","jump-game","Jump Game","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","45","jump-game-ii","Jump Game II","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","274","h-index","H-Index","MEDIUM","Array|Sorting|Counting Sort"],
  ["top-interview-150","Array / String","380","insert-delete-getrandom-o1","Insert Delete GetRandom O(1)","MEDIUM","Array|Hash Table|Math|Design|Randomized"],
  ["top-interview-150","Array / String","238","product-of-array-except-self","Product of Array Except Self","MEDIUM","Array|Prefix Sum"],
  ["top-interview-150","Array / String","134","gas-station","Gas Station","MEDIUM","Array|Greedy"],
  ["top-interview-150","Array / String","135","candy","Candy","HARD","Array|Greedy"],
  ["top-interview-150","Array / String","42","trapping-rain-water","Trapping Rain Water","HARD","Array|Two Pointers|Dynamic Programming|Stack|Monotonic Stack"],
  ["top-interview-150","Array / String","13","roman-to-integer","Roman to Integer","EASY","Hash Table|Math|String"],
  ["top-interview-150","Array / String","12","integer-to-roman","Integer to Roman","MEDIUM","Hash Table|Math|String"],
  ["top-interview-150","Array / String","58","length-of-last-word","Length of Last Word","EASY","String"],
  ["top-interview-150","Array / String","14","longest-common-prefix","Longest Common Prefix","EASY","Array|String|Trie"],
  ["top-interview-150","Array / String","151","reverse-words-in-a-string","Reverse Words in a String","MEDIUM","Two Pointers|String"],
  ["top-interview-150","Array / String","6","zigzag-conversion","Zigzag Conversion","MEDIUM","String"],
  ["top-interview-150","Array / String","28","find-the-index-of-the-first-occurrence-in-a-string","Find the Index of the First Occurrence in a String","EASY","Two Pointers|String|String Matching"],
  ["top-interview-150","Array / String","68","text-justification","Text Justification","HARD","Array|String|Simulation"],
  ["top-interview-150","Two Pointers","125","valid-palindrome","Valid Palindrome","EASY","Two Pointers|String"],
  ["top-interview-150","Two Pointers","392","is-subsequence","Is Subsequence","EASY","Two Pointers|String|Dynamic Programming"],
  ["top-interview-150","Two Pointers","167","two-sum-ii-input-array-is-sorted","Two Sum II - Input Array Is Sorted","MEDIUM","Array|Two Pointers|Binary Search"],
  ["top-interview-150","Two Pointers","11","container-with-most-water","Container With Most Water","MEDIUM","Array|Two Pointers|Greedy"],
  ["top-interview-150","Two Pointers","15","3sum","3Sum","MEDIUM","Array|Two Pointers|Sorting"],
  ["top-interview-150","Sliding Window","209","minimum-size-subarray-sum","Minimum Size Subarray Sum","MEDIUM","Array|Binary Search|Sliding Window|Prefix Sum"],
  ["top-interview-150","Sliding Window","3","longest-substring-without-repeating-characters","Longest Substring Without Repeating Characters","MEDIUM","Hash Table|String|Sliding Window"],
  ["top-interview-150","Sliding Window","30","substring-with-concatenation-of-all-words","Substring with Concatenation of All Words","HARD","Hash Table|String|Sliding Window"],
  ["top-interview-150","Sliding Window","76","minimum-window-substring","Minimum Window Substring","HARD","Hash Table|String|Sliding Window"],
  ["top-interview-150","Matrix","36","valid-sudoku","Valid Sudoku","MEDIUM","Array|Hash Table|Matrix"],
  ["top-interview-150","Matrix","54","spiral-matrix","Spiral Matrix","MEDIUM","Array|Matrix|Simulation"],
  ["top-interview-150","Matrix","48","rotate-image","Rotate Image","MEDIUM","Array|Math|Matrix"],
  ["top-interview-150","Matrix","73","set-matrix-zeroes","Set Matrix Zeroes","MEDIUM","Array|Hash Table|Matrix"],
  ["top-interview-150","Matrix","289","game-of-life","Game of Life","MEDIUM","Array|Matrix|Simulation"],
  ["top-interview-150","Hashmap","383","ransom-note","Ransom Note","EASY","Hash Table|String|Counting"],
  ["top-interview-150","Hashmap","205","isomorphic-strings","Isomorphic Strings","EASY","Hash Table|String"],
  ["top-interview-150","Hashmap","290","word-pattern","Word Pattern","EASY","Hash Table|String"],
  ["top-interview-150","Hashmap","242","valid-anagram","Valid Anagram","EASY","Hash Table|String|Sorting"],
  ["top-interview-150","Hashmap","49","group-anagrams","Group Anagrams","MEDIUM","Array|Hash Table|String|Sorting"],
  ["top-interview-150","Hashmap","1","two-sum","Two Sum","EASY","Array|Hash Table"],
  ["top-interview-150","Hashmap","202","happy-number","Happy Number","EASY","Hash Table|Math|Two Pointers"],
  ["top-interview-150","Hashmap","219","contains-duplicate-ii","Contains Duplicate II","EASY","Array|Hash Table|Sliding Window"],
  ["top-interview-150","Hashmap","128","longest-consecutive-sequence","Longest Consecutive Sequence","MEDIUM","Array|Hash Table|Union-Find"],
  ["top-interview-150","Intervals","228","summary-ranges","Summary Ranges","EASY","Array"],
  ["top-interview-150","Intervals","56","merge-intervals","Merge Intervals","MEDIUM","Array|Sorting"],
  ["top-interview-150","Intervals","57","insert-interval","Insert Interval","MEDIUM","Array"],
  ["top-interview-150","Intervals","452","minimum-number-of-arrows-to-burst-balloons","Minimum Number of Arrows to Burst Balloons","MEDIUM","Array|Greedy|Sorting"],
  ["top-interview-150","Stack","20","valid-parentheses","Valid Parentheses","EASY","String|Stack"],
  ["top-interview-150","Stack","71","simplify-path","Simplify Path","MEDIUM","String|Stack"],
  ["top-interview-150","Stack","155","min-stack","Min Stack","MEDIUM","Stack|Design"],
  ["top-interview-150","Stack","150","evaluate-reverse-polish-notation","Evaluate Reverse Polish Notation","MEDIUM","Array|Math|Stack"],
  ["top-interview-150","Stack","224","basic-calculator","Basic Calculator","HARD","Math|String|Stack|Recursion"],
  ["top-interview-150","Linked List","141","linked-list-cycle","Linked List Cycle","EASY","Hash Table|Linked List|Two Pointers"],
  ["top-interview-150","Linked List","2","add-two-numbers","Add Two Numbers","MEDIUM","Linked List|Math|Recursion"],
  ["top-interview-150","Linked List","21","merge-two-sorted-lists","Merge Two Sorted Lists","EASY","Linked List|Recursion"],
  ["top-interview-150","Linked List","138","copy-list-with-random-pointer","Copy List with Random Pointer","MEDIUM","Hash Table|Linked List"],
  ["top-interview-150","Linked List","92","reverse-linked-list-ii","Reverse Linked List II","MEDIUM","Linked List"],
  ["top-interview-150","Linked List","25","reverse-nodes-in-k-group","Reverse Nodes in k-Group","HARD","Linked List|Recursion"],
  ["top-interview-150","Linked List","19","remove-nth-node-from-end-of-list","Remove Nth Node From End of List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","82","remove-duplicates-from-sorted-list-ii","Remove Duplicates from Sorted List II","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","61","rotate-list","Rotate List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","86","partition-list","Partition List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","146","lru-cache","LRU Cache","MEDIUM","Hash Table|Linked List|Design|Doubly-Linked List"],
  ["top-interview-150","Binary Tree General","104","maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","100","same-tree","Same Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","226","invert-binary-tree","Invert Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","101","symmetric-tree","Symmetric Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","105","construct-binary-tree-from-preorder-and-inorder-traversal","Construct Binary Tree from Preorder and Inorder Traversal","MEDIUM","Array|Hash Table|Divide and Conquer|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","106","construct-binary-tree-from-inorder-and-postorder-traversal","Construct Binary Tree from Inorder and Postorder Traversal","MEDIUM","Array|Hash Table|Divide and Conquer|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","117","populating-next-right-pointers-in-each-node-ii","Populating Next Right Pointers in Each Node II","MEDIUM","Linked List|Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","114","flatten-binary-tree-to-linked-list","Flatten Binary Tree to Linked List","MEDIUM","Linked List|Stack|Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","112","path-sum","Path Sum","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","129","sum-root-to-leaf-numbers","Sum Root to Leaf Numbers","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","124","binary-tree-maximum-path-sum","Binary Tree Maximum Path Sum","HARD","Dynamic Programming|Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","173","binary-search-tree-iterator","Binary Search Tree Iterator","MEDIUM","Stack|Tree|Design|Binary Search Tree|Binary Tree|Iterator"],
  ["top-interview-150","Binary Tree General","222","count-complete-tree-nodes","Count Complete Tree Nodes","EASY","Binary Search|Bit Manipulation|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","236","lowest-common-ancestor-of-a-binary-tree","Lowest Common Ancestor of a Binary Tree","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","199","binary-tree-right-side-view","Binary Tree Right Side View","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","637","average-of-levels-in-binary-tree","Average of Levels in Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","102","binary-tree-level-order-traversal","Binary Tree Level Order Traversal","MEDIUM","Tree|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","103","binary-tree-zigzag-level-order-traversal","Binary Tree Zigzag Level Order Traversal","MEDIUM","Tree|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Search Tree","530","minimum-absolute-difference-in-bst","Minimum Absolute Difference in BST","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Binary Search Tree","230","kth-smallest-element-in-a-bst","Kth Smallest Element in a BST","MEDIUM","Tree|Depth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Binary Search Tree","98","validate-binary-search-tree","Validate Binary Search Tree","MEDIUM","Tree|Depth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Graph General","200","number-of-islands","Number of Islands","MEDIUM","Array|Depth-First Search|Breadth-First Search|Union-Find|Matrix"],
  ["top-interview-150","Graph General","130","surrounded-regions","Surrounded Regions","MEDIUM","Array|Depth-First Search|Breadth-First Search|Union-Find|Matrix"],
  ["top-interview-150","Graph General","133","clone-graph","Clone Graph","MEDIUM","Hash Table|Depth-First Search|Breadth-First Search|Graph Theory"],
  ["top-interview-150","Graph General","399","evaluate-division","Evaluate Division","MEDIUM","Array|String|Depth-First Search|Breadth-First Search|Union-Find|Graph Theory|Shortest Path"],
  ["top-interview-150","Graph General","207","course-schedule","Course Schedule","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory|Topological Sort"],
  ["top-interview-150","Graph General","210","course-schedule-ii","Course Schedule II","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory|Topological Sort"],
  ["top-interview-150","Graph BFS","909","snakes-and-ladders","Snakes and Ladders","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["top-interview-150","Graph BFS","433","minimum-genetic-mutation","Minimum Genetic Mutation","MEDIUM","Hash Table|String|Breadth-First Search"],
  ["top-interview-150","Graph BFS","127","word-ladder","Word Ladder","HARD","Hash Table|String|Breadth-First Search"],
  ["top-interview-150","Trie","208","implement-trie-prefix-tree","Implement Trie (Prefix Tree)","MEDIUM","Hash Table|String|Design|Trie"],
  ["top-interview-150","Trie","211","design-add-and-search-words-data-structure","Design Add and Search Words Data Structure","MEDIUM","String|Depth-First Search|Design|Trie"],
  ["top-interview-150","Trie","212","word-search-ii","Word Search II","HARD","Array|String|Backtracking|Trie|Matrix"],
  ["top-interview-150","Backtracking","17","letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","MEDIUM","Hash Table|String|Backtracking"],
  ["top-interview-150","Backtracking","77","combinations","Combinations","MEDIUM","Backtracking"],
  ["top-interview-150","Backtracking","46","permutations","Permutations","MEDIUM","Array|Backtracking"],
  ["top-interview-150","Backtracking","39","combination-sum","Combination Sum","MEDIUM","Array|Backtracking"],
  ["top-interview-150","Backtracking","52","n-queens-ii","N-Queens II","HARD","Backtracking"],
  ["top-interview-150","Backtracking","22","generate-parentheses","Generate Parentheses","MEDIUM","String|Dynamic Programming|Backtracking"],
  ["top-interview-150","Backtracking","79","word-search","Word Search","MEDIUM","Array|String|Backtracking|Depth-First Search|Matrix"],
  ["top-interview-150","Divide & Conquer","108","convert-sorted-array-to-binary-search-tree","Convert Sorted Array to Binary Search Tree","EASY","Array|Divide and Conquer|Tree|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Divide & Conquer","148","sort-list","Sort List","MEDIUM","Linked List|Two Pointers|Divide and Conquer|Sorting|Merge Sort"],
  ["top-interview-150","Divide & Conquer","427","construct-quad-tree","Construct Quad Tree","MEDIUM","Array|Divide and Conquer|Tree|Matrix"],
  ["top-interview-150","Divide & Conquer","23","merge-k-sorted-lists","Merge k Sorted Lists","HARD","Linked List|Divide and Conquer|Heap (Priority Queue)|Merge Sort"],
  ["top-interview-150","Kadane's Algorithm","53","maximum-subarray","Maximum Subarray","MEDIUM","Array|Divide and Conquer|Dynamic Programming"],
  ["top-interview-150","Kadane's Algorithm","918","maximum-sum-circular-subarray","Maximum Sum Circular Subarray","MEDIUM","Array|Divide and Conquer|Dynamic Programming|Queue|Monotonic Queue"],
  ["top-interview-150","Binary Search","35","search-insert-position","Search Insert Position","EASY","Array|Binary Search"],
  ["top-interview-150","Binary Search","74","search-a-2d-matrix","Search a 2D Matrix","MEDIUM","Array|Binary Search|Matrix"],
  ["top-interview-150","Binary Search","162","find-peak-element","Find Peak Element","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","33","search-in-rotated-sorted-array","Search in Rotated Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","34","find-first-and-last-position-of-element-in-sorted-array","Find First and Last Position of Element in Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","153","find-minimum-in-rotated-sorted-array","Find Minimum in Rotated Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","4","median-of-two-sorted-arrays","Median of Two Sorted Arrays","HARD","Array|Binary Search|Divide and Conquer"],
  ["top-interview-150","Heap","215","kth-largest-element-in-an-array","Kth Largest Element in an Array","MEDIUM","Array|Divide and Conquer|Sorting|Heap (Priority Queue)|Quickselect"],
  ["top-interview-150","Heap","502","ipo","IPO","HARD","Array|Greedy|Sorting|Heap (Priority Queue)"],
  ["top-interview-150","Heap","373","find-k-pairs-with-smallest-sums","Find K Pairs with Smallest Sums","MEDIUM","Array|Heap (Priority Queue)"],
  ["top-interview-150","Heap","295","find-median-from-data-stream","Find Median from Data Stream","HARD","Two Pointers|Design|Sorting|Heap (Priority Queue)|Data Stream"],
  ["top-interview-150","Bit Manipulation","67","add-binary","Add Binary","EASY","Math|String|Bit Manipulation|Simulation"],
  ["top-interview-150","Bit Manipulation","190","reverse-bits","Reverse Bits","EASY","Divide and Conquer|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","191","number-of-1-bits","Number of 1 Bits","EASY","Divide and Conquer|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","136","single-number","Single Number","EASY","Array|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","137","single-number-ii","Single Number II","MEDIUM","Array|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","201","bitwise-and-of-numbers-range","Bitwise AND of Numbers Range","MEDIUM","Bit Manipulation"],
  ["top-interview-150","Math","9","palindrome-number","Palindrome Number","EASY","Math"],
  ["top-interview-150","Math","66","plus-one","Plus One","EASY","Array|Math"],
  ["top-interview-150","Math","172","factorial-trailing-zeroes","Factorial Trailing Zeroes","MEDIUM","Math"],
  ["top-interview-150","Math","69","sqrtx","Sqrt(x)","EASY","Math|Binary Search"],
  ["top-interview-150","Math","50","powx-n","Pow(x, n)","MEDIUM","Math|Recursion"],
  ["top-interview-150","Math","149","max-points-on-a-line","Max Points on a Line","HARD","Array|Hash Table|Math|Geometry"],
  ["top-interview-150","1D DP","70","climbing-stairs","Climbing Stairs","EASY","Math|Dynamic Programming|Memoization"],
  ["top-interview-150","1D DP","198","house-robber","House Robber","MEDIUM","Array|Dynamic Programming"],
  ["top-interview-150","1D DP","139","word-break","Word Break","MEDIUM","Array|Hash Table|String|Dynamic Programming|Trie|Memoization"],
  ["top-interview-150","1D DP","322","coin-change","Coin Change","MEDIUM","Array|Dynamic Programming|Breadth-First Search"],
  ["top-interview-150","1D DP","300","longest-increasing-subsequence","Longest Increasing Subsequence","MEDIUM","Array|Binary Search|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","120","triangle","Triangle","MEDIUM","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","64","minimum-path-sum","Minimum Path Sum","MEDIUM","Array|Dynamic Programming|Matrix"],
  ["top-interview-150","Multidimensional DP","63","unique-paths-ii","Unique Paths II","MEDIUM","Array|Dynamic Programming|Matrix"],
  ["top-interview-150","Multidimensional DP","5","longest-palindromic-substring","Longest Palindromic Substring","MEDIUM","Two Pointers|String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","97","interleaving-string","Interleaving String","MEDIUM","String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","72","edit-distance","Edit Distance","MEDIUM","String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","123","best-time-to-buy-and-sell-stock-iii","Best Time to Buy and Sell Stock III","HARD","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","188","best-time-to-buy-and-sell-stock-iv","Best Time to Buy and Sell Stock IV","HARD","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","221","maximal-square","Maximal Square","MEDIUM","Array|Dynamic Programming|Matrix"],
] as const satisfies readonly RawProblemSetEntry[];
