import type { RawProblemSetEntry } from "./problemSets";

// Generated from official LeetCode study-plan data and NeetCode's public practice bundle.
// Refresh with: node scripts/update-problem-set-data.mjs
export const RAW_PROBLEM_SET_ENTRIES = [
  // LeetCode 75
  ["leetcode-75","Array / String","1768","merge-strings-alternately","Merge Strings Alternately","EASY","Two Pointers|String"],
  ["leetcode-75","Array / String","1071","greatest-common-divisor-of-strings","Greatest Common Divisor of Strings","EASY","Math|String"],
  ["leetcode-75","Array / String","1431","kids-with-the-greatest-number-of-candies","Kids With the Greatest Number of Candies","EASY","Array"],
  ["leetcode-75","Array / String","605","can-place-flowers","Can Place Flowers","EASY","Array|Greedy"],
  ["leetcode-75","Array / String","345","reverse-vowels-of-a-string","Reverse Vowels of a String","EASY","Two Pointers|String"],
  ["leetcode-75","Array / String","151","reverse-words-in-a-string","Reverse Words in a String","MEDIUM","Two Pointers|String"],
  ["leetcode-75","Array / String","238","product-of-array-except-self","Product of Array Except Self","MEDIUM","Array|Prefix Sum"],
  ["leetcode-75","Array / String","334","increasing-triplet-subsequence","Increasing Triplet Subsequence","MEDIUM","Array|Greedy"],
  ["leetcode-75","Array / String","443","string-compression","String Compression","MEDIUM","Two Pointers|String"],
  ["leetcode-75","Two Pointers","283","move-zeroes","Move Zeroes","EASY","Array|Two Pointers"],
  ["leetcode-75","Two Pointers","392","is-subsequence","Is Subsequence","EASY","Two Pointers|String|Dynamic Programming"],
  ["leetcode-75","Two Pointers","11","container-with-most-water","Container With Most Water","MEDIUM","Array|Two Pointers|Greedy"],
  ["leetcode-75","Two Pointers","1679","max-number-of-k-sum-pairs","Max Number of K-Sum Pairs","MEDIUM","Array|Hash Table|Two Pointers|Sorting"],
  ["leetcode-75","Sliding Window","643","maximum-average-subarray-i","Maximum Average Subarray I","EASY","Array|Sliding Window"],
  ["leetcode-75","Sliding Window","1456","maximum-number-of-vowels-in-a-substring-of-given-length","Maximum Number of Vowels in a Substring of Given Length","MEDIUM","String|Sliding Window"],
  ["leetcode-75","Sliding Window","1004","max-consecutive-ones-iii","Max Consecutive Ones III","MEDIUM","Array|Binary Search|Sliding Window|Prefix Sum"],
  ["leetcode-75","Sliding Window","1493","longest-subarray-of-1s-after-deleting-one-element","Longest Subarray of 1's After Deleting One Element","MEDIUM","Array|Dynamic Programming|Sliding Window"],
  ["leetcode-75","Prefix Sum","1732","find-the-highest-altitude","Find the Highest Altitude","EASY","Array|Prefix Sum"],
  ["leetcode-75","Prefix Sum","724","find-pivot-index","Find Pivot Index","EASY","Array|Prefix Sum"],
  ["leetcode-75","Hash Map / Set","2215","find-the-difference-of-two-arrays","Find the Difference of Two Arrays","EASY","Array|Hash Table"],
  ["leetcode-75","Hash Map / Set","1207","unique-number-of-occurrences","Unique Number of Occurrences","EASY","Array|Hash Table"],
  ["leetcode-75","Hash Map / Set","1657","determine-if-two-strings-are-close","Determine if Two Strings Are Close","MEDIUM","Hash Table|String|Sorting|Counting"],
  ["leetcode-75","Hash Map / Set","2352","equal-row-and-column-pairs","Equal Row and Column Pairs","MEDIUM","Array|Hash Table|Matrix|Simulation"],
  ["leetcode-75","Stack","2390","removing-stars-from-a-string","Removing Stars From a String","MEDIUM","String|Stack|Simulation"],
  ["leetcode-75","Stack","735","asteroid-collision","Asteroid Collision","MEDIUM","Array|Stack|Simulation"],
  ["leetcode-75","Stack","394","decode-string","Decode String","MEDIUM","String|Stack|Recursion"],
  ["leetcode-75","Queue","933","number-of-recent-calls","Number of Recent Calls","EASY","Design|Queue|Data Stream"],
  ["leetcode-75","Queue","649","dota2-senate","Dota2 Senate","MEDIUM","String|Greedy|Queue"],
  ["leetcode-75","Linked List","2095","delete-the-middle-node-of-a-linked-list","Delete the Middle Node of a Linked List","MEDIUM","Linked List|Two Pointers"],
  ["leetcode-75","Linked List","328","odd-even-linked-list","Odd Even Linked List","MEDIUM","Linked List"],
  ["leetcode-75","Linked List","206","reverse-linked-list","Reverse Linked List","EASY","Linked List|Recursion"],
  ["leetcode-75","Linked List","2130","maximum-twin-sum-of-a-linked-list","Maximum Twin Sum of a Linked List","MEDIUM","Linked List|Two Pointers|Stack"],
  ["leetcode-75","Binary Tree - DFS","104","maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","872","leaf-similar-trees","Leaf-Similar Trees","EASY","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","1448","count-good-nodes-in-binary-tree","Count Good Nodes in Binary Tree","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","437","path-sum-iii","Path Sum III","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","1372","longest-zigzag-path-in-a-binary-tree","Longest ZigZag Path in a Binary Tree","MEDIUM","Dynamic Programming|Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - DFS","236","lowest-common-ancestor-of-a-binary-tree","Lowest Common Ancestor of a Binary Tree","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - BFS","199","binary-tree-right-side-view","Binary Tree Right Side View","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Tree - BFS","1161","maximum-level-sum-of-a-binary-tree","Maximum Level Sum of a Binary Tree","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["leetcode-75","Binary Search Tree","700","search-in-a-binary-search-tree","Search in a Binary Search Tree","EASY","Tree|Binary Search Tree|Binary Tree"],
  ["leetcode-75","Binary Search Tree","450","delete-node-in-a-bst","Delete Node in a BST","MEDIUM","Tree|Binary Search Tree|Binary Tree"],
  ["leetcode-75","Graphs - DFS","841","keys-and-rooms","Keys and Rooms","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory"],
  ["leetcode-75","Graphs - DFS","547","number-of-provinces","Number of Provinces","MEDIUM","Depth-First Search|Breadth-First Search|Union-Find|Graph Theory"],
  ["leetcode-75","Graphs - DFS","1466","reorder-routes-to-make-all-paths-lead-to-the-city-zero","Reorder Routes to Make All Paths Lead to the City Zero","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory"],
  ["leetcode-75","Graphs - DFS","399","evaluate-division","Evaluate Division","MEDIUM","Array|String|Depth-First Search|Breadth-First Search|Union-Find|Graph Theory|Shortest Path"],
  ["leetcode-75","Graphs - BFS","1926","nearest-exit-from-entrance-in-maze","Nearest Exit from Entrance in Maze","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["leetcode-75","Graphs - BFS","994","rotting-oranges","Rotting Oranges","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["leetcode-75","Heap / Priority Queue","215","kth-largest-element-in-an-array","Kth Largest Element in an Array","MEDIUM","Array|Divide and Conquer|Sorting|Heap (Priority Queue)|Quickselect"],
  ["leetcode-75","Heap / Priority Queue","2336","smallest-number-in-infinite-set","Smallest Number in Infinite Set","MEDIUM","Hash Table|Design|Heap (Priority Queue)|Ordered Set"],
  ["leetcode-75","Heap / Priority Queue","2542","maximum-subsequence-score","Maximum Subsequence Score","MEDIUM","Array|Greedy|Sorting|Heap (Priority Queue)"],
  ["leetcode-75","Heap / Priority Queue","2462","total-cost-to-hire-k-workers","Total Cost to Hire K Workers","MEDIUM","Array|Two Pointers|Heap (Priority Queue)|Simulation"],
  ["leetcode-75","Binary Search","374","guess-number-higher-or-lower","Guess Number Higher or Lower","EASY","Binary Search|Interactive"],
  ["leetcode-75","Binary Search","2300","successful-pairs-of-spells-and-potions","Successful Pairs of Spells and Potions","MEDIUM","Array|Two Pointers|Binary Search|Sorting"],
  ["leetcode-75","Binary Search","162","find-peak-element","Find Peak Element","MEDIUM","Array|Binary Search"],
  ["leetcode-75","Binary Search","875","koko-eating-bananas","Koko Eating Bananas","MEDIUM","Array|Binary Search"],
  ["leetcode-75","Backtracking","17","letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","MEDIUM","Hash Table|String|Backtracking"],
  ["leetcode-75","Backtracking","216","combination-sum-iii","Combination Sum III","MEDIUM","Array|Backtracking"],
  ["leetcode-75","DP - 1D","1137","n-th-tribonacci-number","N-th Tribonacci Number","EASY","Math|Dynamic Programming|Memoization"],
  ["leetcode-75","DP - 1D","746","min-cost-climbing-stairs","Min Cost Climbing Stairs","EASY","Array|Dynamic Programming"],
  ["leetcode-75","DP - 1D","198","house-robber","House Robber","MEDIUM","Array|Dynamic Programming"],
  ["leetcode-75","DP - 1D","790","domino-and-tromino-tiling","Domino and Tromino Tiling","MEDIUM","Dynamic Programming"],
  ["leetcode-75","DP - Multidimensional","62","unique-paths","Unique Paths","MEDIUM","Math|Dynamic Programming|Combinatorics"],
  ["leetcode-75","DP - Multidimensional","1143","longest-common-subsequence","Longest Common Subsequence","MEDIUM","String|Dynamic Programming"],
  ["leetcode-75","DP - Multidimensional","714","best-time-to-buy-and-sell-stock-with-transaction-fee","Best Time to Buy and Sell Stock with Transaction Fee","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["leetcode-75","DP - Multidimensional","72","edit-distance","Edit Distance","MEDIUM","String|Dynamic Programming"],
  ["leetcode-75","Bit Manipulation","338","counting-bits","Counting Bits","EASY","Dynamic Programming|Bit Manipulation"],
  ["leetcode-75","Bit Manipulation","136","single-number","Single Number","EASY","Array|Bit Manipulation"],
  ["leetcode-75","Bit Manipulation","1318","minimum-flips-to-make-a-or-b-equal-to-c","Minimum Flips to Make a OR b Equal to c","MEDIUM","Bit Manipulation"],
  ["leetcode-75","Trie","208","implement-trie-prefix-tree","Implement Trie (Prefix Tree)","MEDIUM","Hash Table|String|Design|Trie"],
  ["leetcode-75","Trie","1268","search-suggestions-system","Search Suggestions System","MEDIUM","Array|String|Binary Search|Trie|Sorting|Heap (Priority Queue)"],
  ["leetcode-75","Intervals","435","non-overlapping-intervals","Non-overlapping Intervals","MEDIUM","Array|Dynamic Programming|Greedy|Sorting"],
  ["leetcode-75","Intervals","452","minimum-number-of-arrows-to-burst-balloons","Minimum Number of Arrows to Burst Balloons","MEDIUM","Array|Greedy|Sorting"],
  ["leetcode-75","Monotonic Stack","739","daily-temperatures","Daily Temperatures","MEDIUM","Array|Stack|Monotonic Stack"],
  ["leetcode-75","Monotonic Stack","901","online-stock-span","Online Stock Span","MEDIUM","Stack|Design|Monotonic Stack|Data Stream"],
  // Top Interview 150
  ["top-interview-150","Array / String","88","merge-sorted-array","Merge Sorted Array","EASY","Array|Two Pointers|Sorting"],
  ["top-interview-150","Array / String","27","remove-element","Remove Element","EASY","Array|Two Pointers"],
  ["top-interview-150","Array / String","26","remove-duplicates-from-sorted-array","Remove Duplicates from Sorted Array","EASY","Array|Two Pointers"],
  ["top-interview-150","Array / String","80","remove-duplicates-from-sorted-array-ii","Remove Duplicates from Sorted Array II","MEDIUM","Array|Two Pointers"],
  ["top-interview-150","Array / String","169","majority-element","Majority Element","EASY","Array|Hash Table|Divide and Conquer|Sorting|Counting"],
  ["top-interview-150","Array / String","189","rotate-array","Rotate Array","MEDIUM","Array|Math|Two Pointers"],
  ["top-interview-150","Array / String","121","best-time-to-buy-and-sell-stock","Best Time to Buy and Sell Stock","EASY","Array|Dynamic Programming"],
  ["top-interview-150","Array / String","122","best-time-to-buy-and-sell-stock-ii","Best Time to Buy and Sell Stock II","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","55","jump-game","Jump Game","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","45","jump-game-ii","Jump Game II","MEDIUM","Array|Dynamic Programming|Greedy"],
  ["top-interview-150","Array / String","274","h-index","H-Index","MEDIUM","Array|Sorting|Counting Sort"],
  ["top-interview-150","Array / String","380","insert-delete-getrandom-o1","Insert Delete GetRandom O(1)","MEDIUM","Array|Hash Table|Math|Design|Randomized"],
  ["top-interview-150","Array / String","238","product-of-array-except-self","Product of Array Except Self","MEDIUM","Array|Prefix Sum"],
  ["top-interview-150","Array / String","134","gas-station","Gas Station","MEDIUM","Array|Greedy"],
  ["top-interview-150","Array / String","135","candy","Candy","HARD","Array|Greedy"],
  ["top-interview-150","Array / String","42","trapping-rain-water","Trapping Rain Water","HARD","Array|Two Pointers|Dynamic Programming|Stack|Monotonic Stack"],
  ["top-interview-150","Array / String","13","roman-to-integer","Roman to Integer","EASY","Hash Table|Math|String"],
  ["top-interview-150","Array / String","12","integer-to-roman","Integer to Roman","MEDIUM","Hash Table|Math|String"],
  ["top-interview-150","Array / String","58","length-of-last-word","Length of Last Word","EASY","String"],
  ["top-interview-150","Array / String","14","longest-common-prefix","Longest Common Prefix","EASY","Array|String|Trie"],
  ["top-interview-150","Array / String","151","reverse-words-in-a-string","Reverse Words in a String","MEDIUM","Two Pointers|String"],
  ["top-interview-150","Array / String","6","zigzag-conversion","Zigzag Conversion","MEDIUM","String"],
  ["top-interview-150","Array / String","28","find-the-index-of-the-first-occurrence-in-a-string","Find the Index of the First Occurrence in a String","EASY","Two Pointers|String|String Matching"],
  ["top-interview-150","Array / String","68","text-justification","Text Justification","HARD","Array|String|Simulation"],
  ["top-interview-150","Two Pointers","125","valid-palindrome","Valid Palindrome","EASY","Two Pointers|String"],
  ["top-interview-150","Two Pointers","392","is-subsequence","Is Subsequence","EASY","Two Pointers|String|Dynamic Programming"],
  ["top-interview-150","Two Pointers","167","two-sum-ii-input-array-is-sorted","Two Sum II - Input Array Is Sorted","MEDIUM","Array|Two Pointers|Binary Search"],
  ["top-interview-150","Two Pointers","11","container-with-most-water","Container With Most Water","MEDIUM","Array|Two Pointers|Greedy"],
  ["top-interview-150","Two Pointers","15","3sum","3Sum","MEDIUM","Array|Two Pointers|Sorting"],
  ["top-interview-150","Sliding Window","209","minimum-size-subarray-sum","Minimum Size Subarray Sum","MEDIUM","Array|Binary Search|Sliding Window|Prefix Sum"],
  ["top-interview-150","Sliding Window","3","longest-substring-without-repeating-characters","Longest Substring Without Repeating Characters","MEDIUM","Hash Table|String|Sliding Window"],
  ["top-interview-150","Sliding Window","30","substring-with-concatenation-of-all-words","Substring with Concatenation of All Words","HARD","Hash Table|String|Sliding Window"],
  ["top-interview-150","Sliding Window","76","minimum-window-substring","Minimum Window Substring","HARD","Hash Table|String|Sliding Window"],
  ["top-interview-150","Matrix","36","valid-sudoku","Valid Sudoku","MEDIUM","Array|Hash Table|Matrix"],
  ["top-interview-150","Matrix","54","spiral-matrix","Spiral Matrix","MEDIUM","Array|Matrix|Simulation"],
  ["top-interview-150","Matrix","48","rotate-image","Rotate Image","MEDIUM","Array|Math|Matrix"],
  ["top-interview-150","Matrix","73","set-matrix-zeroes","Set Matrix Zeroes","MEDIUM","Array|Hash Table|Matrix"],
  ["top-interview-150","Matrix","289","game-of-life","Game of Life","MEDIUM","Array|Matrix|Simulation"],
  ["top-interview-150","Hashmap","383","ransom-note","Ransom Note","EASY","Hash Table|String|Counting"],
  ["top-interview-150","Hashmap","205","isomorphic-strings","Isomorphic Strings","EASY","Hash Table|String"],
  ["top-interview-150","Hashmap","290","word-pattern","Word Pattern","EASY","Hash Table|String"],
  ["top-interview-150","Hashmap","242","valid-anagram","Valid Anagram","EASY","Hash Table|String|Sorting"],
  ["top-interview-150","Hashmap","49","group-anagrams","Group Anagrams","MEDIUM","Array|Hash Table|String|Sorting"],
  ["top-interview-150","Hashmap","1","two-sum","Two Sum","EASY","Array|Hash Table"],
  ["top-interview-150","Hashmap","202","happy-number","Happy Number","EASY","Hash Table|Math|Two Pointers"],
  ["top-interview-150","Hashmap","219","contains-duplicate-ii","Contains Duplicate II","EASY","Array|Hash Table|Sliding Window"],
  ["top-interview-150","Hashmap","128","longest-consecutive-sequence","Longest Consecutive Sequence","MEDIUM","Array|Hash Table|Union-Find"],
  ["top-interview-150","Intervals","228","summary-ranges","Summary Ranges","EASY","Array"],
  ["top-interview-150","Intervals","56","merge-intervals","Merge Intervals","MEDIUM","Array|Sorting"],
  ["top-interview-150","Intervals","57","insert-interval","Insert Interval","MEDIUM","Array"],
  ["top-interview-150","Intervals","452","minimum-number-of-arrows-to-burst-balloons","Minimum Number of Arrows to Burst Balloons","MEDIUM","Array|Greedy|Sorting"],
  ["top-interview-150","Stack","20","valid-parentheses","Valid Parentheses","EASY","String|Stack"],
  ["top-interview-150","Stack","71","simplify-path","Simplify Path","MEDIUM","String|Stack"],
  ["top-interview-150","Stack","155","min-stack","Min Stack","MEDIUM","Stack|Design"],
  ["top-interview-150","Stack","150","evaluate-reverse-polish-notation","Evaluate Reverse Polish Notation","MEDIUM","Array|Math|Stack"],
  ["top-interview-150","Stack","224","basic-calculator","Basic Calculator","HARD","Math|String|Stack|Recursion"],
  ["top-interview-150","Linked List","141","linked-list-cycle","Linked List Cycle","EASY","Hash Table|Linked List|Two Pointers"],
  ["top-interview-150","Linked List","2","add-two-numbers","Add Two Numbers","MEDIUM","Linked List|Math|Recursion"],
  ["top-interview-150","Linked List","21","merge-two-sorted-lists","Merge Two Sorted Lists","EASY","Linked List|Recursion"],
  ["top-interview-150","Linked List","138","copy-list-with-random-pointer","Copy List with Random Pointer","MEDIUM","Hash Table|Linked List"],
  ["top-interview-150","Linked List","92","reverse-linked-list-ii","Reverse Linked List II","MEDIUM","Linked List"],
  ["top-interview-150","Linked List","25","reverse-nodes-in-k-group","Reverse Nodes in k-Group","HARD","Linked List|Recursion"],
  ["top-interview-150","Linked List","19","remove-nth-node-from-end-of-list","Remove Nth Node From End of List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","82","remove-duplicates-from-sorted-list-ii","Remove Duplicates from Sorted List II","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","61","rotate-list","Rotate List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","86","partition-list","Partition List","MEDIUM","Linked List|Two Pointers"],
  ["top-interview-150","Linked List","146","lru-cache","LRU Cache","MEDIUM","Hash Table|Linked List|Design|Doubly-Linked List"],
  ["top-interview-150","Binary Tree General","104","maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","100","same-tree","Same Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","226","invert-binary-tree","Invert Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","101","symmetric-tree","Symmetric Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","105","construct-binary-tree-from-preorder-and-inorder-traversal","Construct Binary Tree from Preorder and Inorder Traversal","MEDIUM","Array|Hash Table|Divide and Conquer|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","106","construct-binary-tree-from-inorder-and-postorder-traversal","Construct Binary Tree from Inorder and Postorder Traversal","MEDIUM","Array|Hash Table|Divide and Conquer|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","117","populating-next-right-pointers-in-each-node-ii","Populating Next Right Pointers in Each Node II","MEDIUM","Linked List|Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","114","flatten-binary-tree-to-linked-list","Flatten Binary Tree to Linked List","MEDIUM","Linked List|Stack|Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","112","path-sum","Path Sum","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","129","sum-root-to-leaf-numbers","Sum Root to Leaf Numbers","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","124","binary-tree-maximum-path-sum","Binary Tree Maximum Path Sum","HARD","Dynamic Programming|Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree General","173","binary-search-tree-iterator","Binary Search Tree Iterator","MEDIUM","Stack|Tree|Design|Binary Search Tree|Binary Tree|Iterator"],
  ["top-interview-150","Binary Tree General","222","count-complete-tree-nodes","Count Complete Tree Nodes","EASY","Binary Search|Bit Manipulation|Tree|Binary Tree"],
  ["top-interview-150","Binary Tree General","236","lowest-common-ancestor-of-a-binary-tree","Lowest Common Ancestor of a Binary Tree","MEDIUM","Tree|Depth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","199","binary-tree-right-side-view","Binary Tree Right Side View","MEDIUM","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","637","average-of-levels-in-binary-tree","Average of Levels in Binary Tree","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","102","binary-tree-level-order-traversal","Binary Tree Level Order Traversal","MEDIUM","Tree|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Tree BFS","103","binary-tree-zigzag-level-order-traversal","Binary Tree Zigzag Level Order Traversal","MEDIUM","Tree|Breadth-First Search|Binary Tree"],
  ["top-interview-150","Binary Search Tree","530","minimum-absolute-difference-in-bst","Minimum Absolute Difference in BST","EASY","Tree|Depth-First Search|Breadth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Binary Search Tree","230","kth-smallest-element-in-a-bst","Kth Smallest Element in a BST","MEDIUM","Tree|Depth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Binary Search Tree","98","validate-binary-search-tree","Validate Binary Search Tree","MEDIUM","Tree|Depth-First Search|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Graph General","200","number-of-islands","Number of Islands","MEDIUM","Array|Depth-First Search|Breadth-First Search|Union-Find|Matrix"],
  ["top-interview-150","Graph General","130","surrounded-regions","Surrounded Regions","MEDIUM","Array|Depth-First Search|Breadth-First Search|Union-Find|Matrix"],
  ["top-interview-150","Graph General","133","clone-graph","Clone Graph","MEDIUM","Hash Table|Depth-First Search|Breadth-First Search|Graph Theory"],
  ["top-interview-150","Graph General","399","evaluate-division","Evaluate Division","MEDIUM","Array|String|Depth-First Search|Breadth-First Search|Union-Find|Graph Theory|Shortest Path"],
  ["top-interview-150","Graph General","207","course-schedule","Course Schedule","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory|Topological Sort"],
  ["top-interview-150","Graph General","210","course-schedule-ii","Course Schedule II","MEDIUM","Depth-First Search|Breadth-First Search|Graph Theory|Topological Sort"],
  ["top-interview-150","Graph BFS","909","snakes-and-ladders","Snakes and Ladders","MEDIUM","Array|Breadth-First Search|Matrix"],
  ["top-interview-150","Graph BFS","433","minimum-genetic-mutation","Minimum Genetic Mutation","MEDIUM","Hash Table|String|Breadth-First Search"],
  ["top-interview-150","Graph BFS","127","word-ladder","Word Ladder","HARD","Hash Table|String|Breadth-First Search"],
  ["top-interview-150","Trie","208","implement-trie-prefix-tree","Implement Trie (Prefix Tree)","MEDIUM","Hash Table|String|Design|Trie"],
  ["top-interview-150","Trie","211","design-add-and-search-words-data-structure","Design Add and Search Words Data Structure","MEDIUM","String|Depth-First Search|Design|Trie"],
  ["top-interview-150","Trie","212","word-search-ii","Word Search II","HARD","Array|String|Backtracking|Trie|Matrix"],
  ["top-interview-150","Backtracking","17","letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","MEDIUM","Hash Table|String|Backtracking"],
  ["top-interview-150","Backtracking","77","combinations","Combinations","MEDIUM","Backtracking"],
  ["top-interview-150","Backtracking","46","permutations","Permutations","MEDIUM","Array|Backtracking"],
  ["top-interview-150","Backtracking","39","combination-sum","Combination Sum","MEDIUM","Array|Backtracking"],
  ["top-interview-150","Backtracking","52","n-queens-ii","N-Queens II","HARD","Backtracking"],
  ["top-interview-150","Backtracking","22","generate-parentheses","Generate Parentheses","MEDIUM","String|Dynamic Programming|Backtracking"],
  ["top-interview-150","Backtracking","79","word-search","Word Search","MEDIUM","Array|String|Backtracking|Depth-First Search|Matrix"],
  ["top-interview-150","Divide & Conquer","108","convert-sorted-array-to-binary-search-tree","Convert Sorted Array to Binary Search Tree","EASY","Array|Divide and Conquer|Tree|Binary Search Tree|Binary Tree"],
  ["top-interview-150","Divide & Conquer","148","sort-list","Sort List","MEDIUM","Linked List|Two Pointers|Divide and Conquer|Sorting|Merge Sort"],
  ["top-interview-150","Divide & Conquer","427","construct-quad-tree","Construct Quad Tree","MEDIUM","Array|Divide and Conquer|Tree|Matrix"],
  ["top-interview-150","Divide & Conquer","23","merge-k-sorted-lists","Merge k Sorted Lists","HARD","Linked List|Divide and Conquer|Heap (Priority Queue)|Merge Sort"],
  ["top-interview-150","Kadane's Algorithm","53","maximum-subarray","Maximum Subarray","MEDIUM","Array|Divide and Conquer|Dynamic Programming"],
  ["top-interview-150","Kadane's Algorithm","918","maximum-sum-circular-subarray","Maximum Sum Circular Subarray","MEDIUM","Array|Divide and Conquer|Dynamic Programming|Queue|Monotonic Queue"],
  ["top-interview-150","Binary Search","35","search-insert-position","Search Insert Position","EASY","Array|Binary Search"],
  ["top-interview-150","Binary Search","74","search-a-2d-matrix","Search a 2D Matrix","MEDIUM","Array|Binary Search|Matrix"],
  ["top-interview-150","Binary Search","162","find-peak-element","Find Peak Element","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","33","search-in-rotated-sorted-array","Search in Rotated Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","34","find-first-and-last-position-of-element-in-sorted-array","Find First and Last Position of Element in Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","153","find-minimum-in-rotated-sorted-array","Find Minimum in Rotated Sorted Array","MEDIUM","Array|Binary Search"],
  ["top-interview-150","Binary Search","4","median-of-two-sorted-arrays","Median of Two Sorted Arrays","HARD","Array|Binary Search|Divide and Conquer"],
  ["top-interview-150","Heap","215","kth-largest-element-in-an-array","Kth Largest Element in an Array","MEDIUM","Array|Divide and Conquer|Sorting|Heap (Priority Queue)|Quickselect"],
  ["top-interview-150","Heap","502","ipo","IPO","HARD","Array|Greedy|Sorting|Heap (Priority Queue)"],
  ["top-interview-150","Heap","373","find-k-pairs-with-smallest-sums","Find K Pairs with Smallest Sums","MEDIUM","Array|Heap (Priority Queue)"],
  ["top-interview-150","Heap","295","find-median-from-data-stream","Find Median from Data Stream","HARD","Two Pointers|Design|Sorting|Heap (Priority Queue)|Data Stream"],
  ["top-interview-150","Bit Manipulation","67","add-binary","Add Binary","EASY","Math|String|Bit Manipulation|Simulation"],
  ["top-interview-150","Bit Manipulation","190","reverse-bits","Reverse Bits","EASY","Divide and Conquer|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","191","number-of-1-bits","Number of 1 Bits","EASY","Divide and Conquer|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","136","single-number","Single Number","EASY","Array|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","137","single-number-ii","Single Number II","MEDIUM","Array|Bit Manipulation"],
  ["top-interview-150","Bit Manipulation","201","bitwise-and-of-numbers-range","Bitwise AND of Numbers Range","MEDIUM","Bit Manipulation"],
  ["top-interview-150","Math","9","palindrome-number","Palindrome Number","EASY","Math"],
  ["top-interview-150","Math","66","plus-one","Plus One","EASY","Array|Math"],
  ["top-interview-150","Math","172","factorial-trailing-zeroes","Factorial Trailing Zeroes","MEDIUM","Math"],
  ["top-interview-150","Math","69","sqrtx","Sqrt(x)","EASY","Math|Binary Search"],
  ["top-interview-150","Math","50","powx-n","Pow(x, n)","MEDIUM","Math|Recursion"],
  ["top-interview-150","Math","149","max-points-on-a-line","Max Points on a Line","HARD","Array|Hash Table|Math|Geometry"],
  ["top-interview-150","1D DP","70","climbing-stairs","Climbing Stairs","EASY","Math|Dynamic Programming|Memoization"],
  ["top-interview-150","1D DP","198","house-robber","House Robber","MEDIUM","Array|Dynamic Programming"],
  ["top-interview-150","1D DP","139","word-break","Word Break","MEDIUM","Array|Hash Table|String|Dynamic Programming|Trie|Memoization"],
  ["top-interview-150","1D DP","322","coin-change","Coin Change","MEDIUM","Array|Dynamic Programming|Breadth-First Search"],
  ["top-interview-150","1D DP","300","longest-increasing-subsequence","Longest Increasing Subsequence","MEDIUM","Array|Binary Search|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","120","triangle","Triangle","MEDIUM","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","64","minimum-path-sum","Minimum Path Sum","MEDIUM","Array|Dynamic Programming|Matrix"],
  ["top-interview-150","Multidimensional DP","63","unique-paths-ii","Unique Paths II","MEDIUM","Array|Dynamic Programming|Matrix"],
  ["top-interview-150","Multidimensional DP","5","longest-palindromic-substring","Longest Palindromic Substring","MEDIUM","Two Pointers|String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","97","interleaving-string","Interleaving String","MEDIUM","String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","72","edit-distance","Edit Distance","MEDIUM","String|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","123","best-time-to-buy-and-sell-stock-iii","Best Time to Buy and Sell Stock III","HARD","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","188","best-time-to-buy-and-sell-stock-iv","Best Time to Buy and Sell Stock IV","HARD","Array|Dynamic Programming"],
  ["top-interview-150","Multidimensional DP","221","maximal-square","Maximal Square","MEDIUM","Array|Dynamic Programming|Matrix"],
  // NeetCode 150
  ["neetcode-150","Arrays & Hashing","217","contains-duplicate","Contains Duplicate","EASY","Arrays & Hashing","duplicate-integer"],
  ["neetcode-150","Arrays & Hashing","242","valid-anagram","Valid Anagram","EASY","Arrays & Hashing","is-anagram"],
  ["neetcode-150","Arrays & Hashing","1","two-sum","Two Sum","EASY","Arrays & Hashing","two-integer-sum"],
  ["neetcode-150","Arrays & Hashing","49","group-anagrams","Group Anagrams","MEDIUM","Arrays & Hashing","anagram-groups"],
  ["neetcode-150","Arrays & Hashing","347","top-k-frequent-elements","Top K Frequent Elements","MEDIUM","Arrays & Hashing","top-k-elements-in-list"],
  ["neetcode-150","Arrays & Hashing","271","encode-and-decode-strings","Encode and Decode Strings","MEDIUM","Arrays & Hashing","string-encode-and-decode"],
  ["neetcode-150","Arrays & Hashing","238","product-of-array-except-self","Product of Array Except Self","MEDIUM","Arrays & Hashing","products-of-array-discluding-self"],
  ["neetcode-150","Arrays & Hashing","36","valid-sudoku","Valid Sudoku","MEDIUM","Arrays & Hashing","valid-sudoku"],
  ["neetcode-150","Arrays & Hashing","128","longest-consecutive-sequence","Longest Consecutive Sequence","MEDIUM","Arrays & Hashing","longest-consecutive-sequence"],
  ["neetcode-150","Two Pointers","125","valid-palindrome","Valid Palindrome","EASY","Two Pointers","is-palindrome"],
  ["neetcode-150","Two Pointers","167","two-sum-ii-input-array-is-sorted","Two Sum II Input Array Is Sorted","MEDIUM","Two Pointers","two-integer-sum-ii"],
  ["neetcode-150","Two Pointers","15","3sum","3Sum","MEDIUM","Two Pointers","three-integer-sum"],
  ["neetcode-150","Two Pointers","11","container-with-most-water","Container With Most Water","MEDIUM","Two Pointers","max-water-container"],
  ["neetcode-150","Two Pointers","42","trapping-rain-water","Trapping Rain Water","HARD","Two Pointers","trapping-rain-water"],
  ["neetcode-150","Sliding Window","121","best-time-to-buy-and-sell-stock","Best Time to Buy And Sell Stock","EASY","Sliding Window","buy-and-sell-crypto"],
  ["neetcode-150","Sliding Window","3","longest-substring-without-repeating-characters","Longest Substring Without Repeating Characters","MEDIUM","Sliding Window","longest-substring-without-duplicates"],
  ["neetcode-150","Sliding Window","424","longest-repeating-character-replacement","Longest Repeating Character Replacement","MEDIUM","Sliding Window","longest-repeating-substring-with-replacement"],
  ["neetcode-150","Sliding Window","567","permutation-in-string","Permutation In String","MEDIUM","Sliding Window","permutation-string"],
  ["neetcode-150","Sliding Window","76","minimum-window-substring","Minimum Window Substring","HARD","Sliding Window","minimum-window-with-characters"],
  ["neetcode-150","Sliding Window","239","sliding-window-maximum","Sliding Window Maximum","HARD","Sliding Window","sliding-window-maximum"],
  ["neetcode-150","Stack","20","valid-parentheses","Valid Parentheses","EASY","Stack","validate-parentheses"],
  ["neetcode-150","Stack","155","min-stack","Min Stack","MEDIUM","Stack","minimum-stack"],
  ["neetcode-150","Stack","150","evaluate-reverse-polish-notation","Evaluate Reverse Polish Notation","MEDIUM","Stack","evaluate-reverse-polish-notation"],
  ["neetcode-150","Stack","739","daily-temperatures","Daily Temperatures","MEDIUM","Stack","daily-temperatures"],
  ["neetcode-150","Stack","853","car-fleet","Car Fleet","MEDIUM","Stack","car-fleet"],
  ["neetcode-150","Stack","84","largest-rectangle-in-histogram","Largest Rectangle In Histogram","HARD","Stack","largest-rectangle-in-histogram"],
  ["neetcode-150","Binary Search","704","binary-search","Binary Search","EASY","Binary Search","binary-search"],
  ["neetcode-150","Binary Search","74","search-a-2d-matrix","Search a 2D Matrix","MEDIUM","Binary Search","search-2d-matrix"],
  ["neetcode-150","Binary Search","875","koko-eating-bananas","Koko Eating Bananas","MEDIUM","Binary Search","eating-bananas"],
  ["neetcode-150","Binary Search","153","find-minimum-in-rotated-sorted-array","Find Minimum In Rotated Sorted Array","MEDIUM","Binary Search","find-minimum-in-rotated-sorted-array"],
  ["neetcode-150","Binary Search","33","search-in-rotated-sorted-array","Search In Rotated Sorted Array","MEDIUM","Binary Search","find-target-in-rotated-sorted-array"],
  ["neetcode-150","Binary Search","981","time-based-key-value-store","Time Based Key Value Store","MEDIUM","Binary Search","time-based-key-value-store"],
  ["neetcode-150","Binary Search","4","median-of-two-sorted-arrays","Median of Two Sorted Arrays","HARD","Binary Search","median-of-two-sorted-arrays"],
  ["neetcode-150","Linked List","206","reverse-linked-list","Reverse Linked List","EASY","Linked List","reverse-a-linked-list"],
  ["neetcode-150","Linked List","21","merge-two-sorted-lists","Merge Two Sorted Lists","EASY","Linked List","merge-two-sorted-linked-lists"],
  ["neetcode-150","Linked List","141","linked-list-cycle","Linked List Cycle","EASY","Linked List","linked-list-cycle-detection"],
  ["neetcode-150","Linked List","143","reorder-list","Reorder List","MEDIUM","Linked List","reorder-linked-list"],
  ["neetcode-150","Linked List","19","remove-nth-node-from-end-of-list","Remove Nth Node From End of List","MEDIUM","Linked List","remove-node-from-end-of-linked-list"],
  ["neetcode-150","Linked List","138","copy-list-with-random-pointer","Copy List With Random Pointer","MEDIUM","Linked List","copy-linked-list-with-random-pointer"],
  ["neetcode-150","Linked List","2","add-two-numbers","Add Two Numbers","MEDIUM","Linked List","add-two-numbers"],
  ["neetcode-150","Linked List","287","find-the-duplicate-number","Find The Duplicate Number","MEDIUM","Linked List","find-duplicate-integer"],
  ["neetcode-150","Linked List","146","lru-cache","LRU Cache","MEDIUM","Linked List","lru-cache"],
  ["neetcode-150","Linked List","23","merge-k-sorted-lists","Merge K Sorted Lists","HARD","Linked List","merge-k-sorted-linked-lists"],
  ["neetcode-150","Linked List","25","reverse-nodes-in-k-group","Reverse Nodes In K Group","HARD","Linked List","reverse-nodes-in-k-group"],
  ["neetcode-150","Trees","226","invert-binary-tree","Invert Binary Tree","EASY","Trees","invert-a-binary-tree"],
  ["neetcode-150","Trees","104","maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","EASY","Trees","depth-of-binary-tree"],
  ["neetcode-150","Trees","543","diameter-of-binary-tree","Diameter of Binary Tree","EASY","Trees","binary-tree-diameter"],
  ["neetcode-150","Trees","110","balanced-binary-tree","Balanced Binary Tree","EASY","Trees","balanced-binary-tree"],
  ["neetcode-150","Trees","100","same-tree","Same Tree","EASY","Trees","same-binary-tree"],
  ["neetcode-150","Trees","572","subtree-of-another-tree","Subtree of Another Tree","EASY","Trees","subtree-of-a-binary-tree"],
  ["neetcode-150","Trees","235","lowest-common-ancestor-of-a-binary-search-tree","Lowest Common Ancestor of a Binary Search Tree","MEDIUM","Trees","lowest-common-ancestor-in-binary-search-tree"],
  ["neetcode-150","Trees","102","binary-tree-level-order-traversal","Binary Tree Level Order Traversal","MEDIUM","Trees","level-order-traversal-of-binary-tree"],
  ["neetcode-150","Trees","199","binary-tree-right-side-view","Binary Tree Right Side View","MEDIUM","Trees","binary-tree-right-side-view"],
  ["neetcode-150","Trees","1448","count-good-nodes-in-binary-tree","Count Good Nodes In Binary Tree","MEDIUM","Trees","count-good-nodes-in-binary-tree"],
  ["neetcode-150","Trees","98","validate-binary-search-tree","Validate Binary Search Tree","MEDIUM","Trees","valid-binary-search-tree"],
  ["neetcode-150","Trees","230","kth-smallest-element-in-a-bst","Kth Smallest Element In a Bst","MEDIUM","Trees","kth-smallest-integer-in-bst"],
  ["neetcode-150","Trees","105","construct-binary-tree-from-preorder-and-inorder-traversal","Construct Binary Tree From Preorder And Inorder Traversal","MEDIUM","Trees","binary-tree-from-preorder-and-inorder-traversal"],
  ["neetcode-150","Trees","124","binary-tree-maximum-path-sum","Binary Tree Maximum Path Sum","HARD","Trees","binary-tree-maximum-path-sum"],
  ["neetcode-150","Trees","297","serialize-and-deserialize-binary-tree","Serialize And Deserialize Binary Tree","HARD","Trees","serialize-and-deserialize-binary-tree"],
  ["neetcode-150","Heap / Priority Queue","703","kth-largest-element-in-a-stream","Kth Largest Element In a Stream","EASY","Heap / Priority Queue","kth-largest-integer-in-a-stream"],
  ["neetcode-150","Heap / Priority Queue","1046","last-stone-weight","Last Stone Weight","EASY","Heap / Priority Queue","last-stone-weight"],
  ["neetcode-150","Heap / Priority Queue","973","k-closest-points-to-origin","K Closest Points to Origin","MEDIUM","Heap / Priority Queue","k-closest-points-to-origin"],
  ["neetcode-150","Heap / Priority Queue","215","kth-largest-element-in-an-array","Kth Largest Element In An Array","MEDIUM","Heap / Priority Queue","kth-largest-element-in-an-array"],
  ["neetcode-150","Heap / Priority Queue","621","task-scheduler","Task Scheduler","MEDIUM","Heap / Priority Queue","task-scheduling"],
  ["neetcode-150","Heap / Priority Queue","355","design-twitter","Design Twitter","MEDIUM","Heap / Priority Queue","design-twitter-feed"],
  ["neetcode-150","Heap / Priority Queue","295","find-median-from-data-stream","Find Median From Data Stream","HARD","Heap / Priority Queue","find-median-in-a-data-stream"],
  ["neetcode-150","Backtracking","78","subsets","Subsets","MEDIUM","Backtracking","subsets"],
  ["neetcode-150","Backtracking","39","combination-sum","Combination Sum","MEDIUM","Backtracking","combination-target-sum"],
  ["neetcode-150","Backtracking","40","combination-sum-ii","Combination Sum II","MEDIUM","Backtracking","combination-target-sum-ii"],
  ["neetcode-150","Backtracking","46","permutations","Permutations","MEDIUM","Backtracking","permutations"],
  ["neetcode-150","Backtracking","90","subsets-ii","Subsets II","MEDIUM","Backtracking","subsets-ii"],
  ["neetcode-150","Backtracking","22","generate-parentheses","Generate Parentheses","MEDIUM","Backtracking","generate-parentheses"],
  ["neetcode-150","Backtracking","79","word-search","Word Search","MEDIUM","Backtracking","search-for-word"],
  ["neetcode-150","Backtracking","131","palindrome-partitioning","Palindrome Partitioning","MEDIUM","Backtracking","palindrome-partitioning"],
  ["neetcode-150","Backtracking","17","letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","MEDIUM","Backtracking","combinations-of-a-phone-number"],
  ["neetcode-150","Backtracking","51","n-queens","N Queens","HARD","Backtracking","n-queens"],
  ["neetcode-150","Tries","208","implement-trie-prefix-tree","Implement Trie Prefix Tree","MEDIUM","Tries","implement-prefix-tree"],
  ["neetcode-150","Tries","211","design-add-and-search-words-data-structure","Design Add And Search Words Data Structure","MEDIUM","Tries","design-word-search-data-structure"],
  ["neetcode-150","Tries","212","word-search-ii","Word Search II","HARD","Tries","search-for-word-ii"],
  ["neetcode-150","Graphs","200","number-of-islands","Number of Islands","MEDIUM","Graphs","count-number-of-islands"],
  ["neetcode-150","Graphs","695","max-area-of-island","Max Area of Island","MEDIUM","Graphs","max-area-of-island"],
  ["neetcode-150","Graphs","133","clone-graph","Clone Graph","MEDIUM","Graphs","clone-graph"],
  ["neetcode-150","Graphs","286","walls-and-gates","Walls And Gates","MEDIUM","Graphs","islands-and-treasure"],
  ["neetcode-150","Graphs","994","rotting-oranges","Rotting Oranges","MEDIUM","Graphs","rotting-fruit"],
  ["neetcode-150","Graphs","417","pacific-atlantic-water-flow","Pacific Atlantic Water Flow","MEDIUM","Graphs","pacific-atlantic-water-flow"],
  ["neetcode-150","Graphs","130","surrounded-regions","Surrounded Regions","MEDIUM","Graphs","surrounded-regions"],
  ["neetcode-150","Graphs","207","course-schedule","Course Schedule","MEDIUM","Graphs","course-schedule"],
  ["neetcode-150","Graphs","210","course-schedule-ii","Course Schedule II","MEDIUM","Graphs","course-schedule-ii"],
  ["neetcode-150","Graphs","261","graph-valid-tree","Graph Valid Tree","MEDIUM","Graphs","valid-tree"],
  ["neetcode-150","Graphs","323","number-of-connected-components-in-an-undirected-graph","Number of Connected Components In An Undirected Graph","MEDIUM","Graphs","count-connected-components"],
  ["neetcode-150","Graphs","684","redundant-connection","Redundant Connection","MEDIUM","Graphs","redundant-connection"],
  ["neetcode-150","Graphs","127","word-ladder","Word Ladder","HARD","Graphs","word-ladder"],
  ["neetcode-150","Advanced Graphs","743","network-delay-time","Network Delay Time","MEDIUM","Advanced Graphs","network-delay-time"],
  ["neetcode-150","Advanced Graphs","332","reconstruct-itinerary","Reconstruct Itinerary","HARD","Advanced Graphs","reconstruct-flight-path"],
  ["neetcode-150","Advanced Graphs","1584","min-cost-to-connect-all-points","Min Cost to Connect All Points","MEDIUM","Advanced Graphs","min-cost-to-connect-points"],
  ["neetcode-150","Advanced Graphs","778","swim-in-rising-water","Swim In Rising Water","HARD","Advanced Graphs","swim-in-rising-water"],
  ["neetcode-150","Advanced Graphs","269","alien-dictionary","Alien Dictionary","HARD","Advanced Graphs","foreign-dictionary"],
  ["neetcode-150","Advanced Graphs","787","cheapest-flights-within-k-stops","Cheapest Flights Within K Stops","MEDIUM","Advanced Graphs","cheapest-flight-path"],
  ["neetcode-150","1-D Dynamic Programming","70","climbing-stairs","Climbing Stairs","EASY","1-D Dynamic Programming","climbing-stairs"],
  ["neetcode-150","1-D Dynamic Programming","746","min-cost-climbing-stairs","Min Cost Climbing Stairs","EASY","1-D Dynamic Programming","min-cost-climbing-stairs"],
  ["neetcode-150","1-D Dynamic Programming","198","house-robber","House Robber","MEDIUM","1-D Dynamic Programming","house-robber"],
  ["neetcode-150","1-D Dynamic Programming","213","house-robber-ii","House Robber II","MEDIUM","1-D Dynamic Programming","house-robber-ii"],
  ["neetcode-150","1-D Dynamic Programming","5","longest-palindromic-substring","Longest Palindromic Substring","MEDIUM","1-D Dynamic Programming","longest-palindromic-substring"],
  ["neetcode-150","1-D Dynamic Programming","647","palindromic-substrings","Palindromic Substrings","MEDIUM","1-D Dynamic Programming","palindromic-substrings"],
  ["neetcode-150","1-D Dynamic Programming","91","decode-ways","Decode Ways","MEDIUM","1-D Dynamic Programming","decode-ways"],
  ["neetcode-150","1-D Dynamic Programming","322","coin-change","Coin Change","MEDIUM","1-D Dynamic Programming","coin-change"],
  ["neetcode-150","1-D Dynamic Programming","152","maximum-product-subarray","Maximum Product Subarray","MEDIUM","1-D Dynamic Programming","maximum-product-subarray"],
  ["neetcode-150","1-D Dynamic Programming","139","word-break","Word Break","MEDIUM","1-D Dynamic Programming","word-break"],
  ["neetcode-150","1-D Dynamic Programming","300","longest-increasing-subsequence","Longest Increasing Subsequence","MEDIUM","1-D Dynamic Programming","longest-increasing-subsequence"],
  ["neetcode-150","1-D Dynamic Programming","416","partition-equal-subset-sum","Partition Equal Subset Sum","MEDIUM","1-D Dynamic Programming","partition-equal-subset-sum"],
  ["neetcode-150","2-D Dynamic Programming","62","unique-paths","Unique Paths","MEDIUM","2-D Dynamic Programming","count-paths"],
  ["neetcode-150","2-D Dynamic Programming","1143","longest-common-subsequence","Longest Common Subsequence","MEDIUM","2-D Dynamic Programming","longest-common-subsequence"],
  ["neetcode-150","2-D Dynamic Programming","309","best-time-to-buy-and-sell-stock-with-cooldown","Best Time to Buy And Sell Stock With Cooldown","MEDIUM","2-D Dynamic Programming","buy-and-sell-crypto-with-cooldown"],
  ["neetcode-150","2-D Dynamic Programming","518","coin-change-ii","Coin Change II","MEDIUM","2-D Dynamic Programming","coin-change-ii"],
  ["neetcode-150","2-D Dynamic Programming","494","target-sum","Target Sum","MEDIUM","2-D Dynamic Programming","target-sum"],
  ["neetcode-150","2-D Dynamic Programming","97","interleaving-string","Interleaving String","MEDIUM","2-D Dynamic Programming","interleaving-string"],
  ["neetcode-150","2-D Dynamic Programming","329","longest-increasing-path-in-a-matrix","Longest Increasing Path In a Matrix","HARD","2-D Dynamic Programming","longest-increasing-path-in-matrix"],
  ["neetcode-150","2-D Dynamic Programming","115","distinct-subsequences","Distinct Subsequences","HARD","2-D Dynamic Programming","count-subsequences"],
  ["neetcode-150","2-D Dynamic Programming","72","edit-distance","Edit Distance","MEDIUM","2-D Dynamic Programming","edit-distance"],
  ["neetcode-150","2-D Dynamic Programming","312","burst-balloons","Burst Balloons","HARD","2-D Dynamic Programming","burst-balloons"],
  ["neetcode-150","2-D Dynamic Programming","10","regular-expression-matching","Regular Expression Matching","HARD","2-D Dynamic Programming","regular-expression-matching"],
  ["neetcode-150","Greedy","53","maximum-subarray","Maximum Subarray","MEDIUM","Greedy","maximum-subarray"],
  ["neetcode-150","Greedy","55","jump-game","Jump Game","MEDIUM","Greedy","jump-game"],
  ["neetcode-150","Greedy","45","jump-game-ii","Jump Game II","MEDIUM","Greedy","jump-game-ii"],
  ["neetcode-150","Greedy","134","gas-station","Gas Station","MEDIUM","Greedy","gas-station"],
  ["neetcode-150","Greedy","846","hand-of-straights","Hand of Straights","MEDIUM","Greedy","hand-of-straights"],
  ["neetcode-150","Greedy","1899","merge-triplets-to-form-target-triplet","Merge Triplets to Form Target Triplet","MEDIUM","Greedy","merge-triplets-to-form-target"],
  ["neetcode-150","Greedy","763","partition-labels","Partition Labels","MEDIUM","Greedy","partition-labels"],
  ["neetcode-150","Greedy","678","valid-parenthesis-string","Valid Parenthesis String","MEDIUM","Greedy","valid-parenthesis-string"],
  ["neetcode-150","Intervals","57","insert-interval","Insert Interval","MEDIUM","Intervals","insert-new-interval"],
  ["neetcode-150","Intervals","56","merge-intervals","Merge Intervals","MEDIUM","Intervals","merge-intervals"],
  ["neetcode-150","Intervals","435","non-overlapping-intervals","Non Overlapping Intervals","MEDIUM","Intervals","non-overlapping-intervals"],
  ["neetcode-150","Intervals","252","meeting-rooms","Meeting Rooms","EASY","Intervals","meeting-schedule"],
  ["neetcode-150","Intervals","253","meeting-rooms-ii","Meeting Rooms II","MEDIUM","Intervals","meeting-schedule-ii"],
  ["neetcode-150","Intervals","1851","minimum-interval-to-include-each-query","Minimum Interval to Include Each Query","HARD","Intervals","minimum-interval-including-query"],
  ["neetcode-150","Math & Geometry","48","rotate-image","Rotate Image","MEDIUM","Math & Geometry","rotate-matrix"],
  ["neetcode-150","Math & Geometry","54","spiral-matrix","Spiral Matrix","MEDIUM","Math & Geometry","spiral-matrix"],
  ["neetcode-150","Math & Geometry","73","set-matrix-zeroes","Set Matrix Zeroes","MEDIUM","Math & Geometry","set-zeroes-in-matrix"],
  ["neetcode-150","Math & Geometry","202","happy-number","Happy Number","EASY","Math & Geometry","non-cyclical-number"],
  ["neetcode-150","Math & Geometry","66","plus-one","Plus One","EASY","Math & Geometry","plus-one"],
  ["neetcode-150","Math & Geometry","50","powx-n","Pow(x, n)","MEDIUM","Math & Geometry","pow-x-n"],
  ["neetcode-150","Math & Geometry","43","multiply-strings","Multiply Strings","MEDIUM","Math & Geometry","multiply-strings"],
  ["neetcode-150","Math & Geometry","2013","detect-squares","Detect Squares","MEDIUM","Math & Geometry","count-squares"],
  ["neetcode-150","Bit Manipulation","136","single-number","Single Number","EASY","Bit Manipulation","single-number"],
  ["neetcode-150","Bit Manipulation","191","number-of-1-bits","Number of 1 Bits","EASY","Bit Manipulation","number-of-one-bits"],
  ["neetcode-150","Bit Manipulation","338","counting-bits","Counting Bits","EASY","Bit Manipulation","counting-bits"],
  ["neetcode-150","Bit Manipulation","190","reverse-bits","Reverse Bits","EASY","Bit Manipulation","reverse-bits"],
  ["neetcode-150","Bit Manipulation","268","missing-number","Missing Number","EASY","Bit Manipulation","missing-number"],
  ["neetcode-150","Bit Manipulation","371","sum-of-two-integers","Sum of Two Integers","MEDIUM","Bit Manipulation","sum-of-two-integers"],
  ["neetcode-150","Bit Manipulation","7","reverse-integer","Reverse Integer","MEDIUM","Bit Manipulation","reverse-integer"],
] as const satisfies readonly RawProblemSetEntry[];
